/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/achievements` | `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/social` | `/social`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/01-welcome` | `/01-welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/02-philosophy` | `/02-philosophy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/03-rex-intro` | `/03-rex-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/04-first-action` | `/04-first-action`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/achievements` | `/achievements`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/log` | `/log`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/social` | `/social`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/01-welcome` | `/01-welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/02-philosophy` | `/02-philosophy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/03-rex-intro` | `/03-rex-intro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/04-first-action` | `/04-first-action`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/achievements${`?${string}` | `#${string}` | ''}` | `/achievements${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/log${`?${string}` | `#${string}` | ''}` | `/log${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/social${`?${string}` | `#${string}` | ''}` | `/social${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/01-welcome${`?${string}` | `#${string}` | ''}` | `/01-welcome${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/02-philosophy${`?${string}` | `#${string}` | ''}` | `/02-philosophy${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/03-rex-intro${`?${string}` | `#${string}` | ''}` | `/03-rex-intro${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/04-first-action${`?${string}` | `#${string}` | ''}` | `/04-first-action${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/achievements` | `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/social` | `/social`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/01-welcome` | `/01-welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/02-philosophy` | `/02-philosophy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/03-rex-intro` | `/03-rex-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/04-first-action` | `/04-first-action`; params?: Router.UnknownInputParams; };
    }
  }
}
